"""Remove content field from newsletters

Revision ID: 08efa37f9d0b
Revises: bf08b82670ae
Create Date: 2026-06-29 19:18:22.937113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08efa37f9d0b'
down_revision = 'bf08b82670ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.alter_column('excerpt',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=True))
        batch_op.alter_column('excerpt',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
