"""Add hero slide CTA fields and blog SEO fields

Revision ID: 090f99eedf14
Revises: 08efa37f9d0b
Create Date: 2026-06-30 08:32:00.373760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '090f99eedf14'
down_revision = '08efa37f9d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_description', sa.String(length=320), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reading_time', sa.Integer(), nullable=True))
        batch_op.alter_column('excerpt',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('hero_slides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('btn_text', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('btn_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('alt_text', sa.String(length=500), nullable=True))

    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.alter_column('excerpt',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=True))
        batch_op.alter_column('excerpt',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('hero_slides', schema=None) as batch_op:
        batch_op.drop_column('alt_text')
        batch_op.drop_column('btn_url')
        batch_op.drop_column('btn_text')

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('excerpt',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('reading_time')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('meta_description')

    # ### end Alembic commands ###
