"""updating newsletter model

Revision ID: 14b80be964bb
Revises: e3aaff484913
Create Date: 2026-06-18 12:12:32.196527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14b80be964bb'
down_revision = 'e3aaff484913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newsletter_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('sent_count')
        batch_op.drop_column('subject')
        batch_op.drop_column('is_sent')
        batch_op.drop_column('pdf_url')
        batch_op.drop_column('sent_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('pdf_url', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_sent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subject', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('sent_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=False))

    op.drop_table('newsletter_campaigns')
    # ### end Alembic commands ###
