"""empty message

Revision ID: b6873d26cd08
Revises: cb5c506e105d
Create Date: 2026-06-24 18:48:30.655158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6873d26cd08'
down_revision = 'cb5c506e105d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('client_company', sa.String(length=255), nullable=True))

    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_company', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.drop_column('client_company')

    with op.batch_alter_table('testimonial_submissions', schema=None) as batch_op:
        batch_op.drop_column('client_company')
        batch_op.drop_column('client_name')

    # ### end Alembic commands ###
