"""added_testimonial_submission

Revision ID: c675ae9d35e6
Revises: e62ebfc75cab
Create Date: 2026-06-24 15:58:25.228183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c675ae9d35e6'
down_revision = 'e62ebfc75cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonial_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_company', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('testimonial_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['testimonial_id'], ['testimonials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('testimonial_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_testimonial_submissions_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_testimonial_submissions_token'))

    op.drop_table('testimonial_submissions')
    # ### end Alembic commands ###
