"""empty message

Revision ID: cb5c506e105d
Revises: c675ae9d35e6
Create Date: 2026-06-24 18:15:46.638330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb5c506e105d'
down_revision = 'c675ae9d35e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial_submissions', schema=None) as batch_op:
        batch_op.drop_column('client_name')
        batch_op.drop_column('client_company')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_company', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('client_name', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
