"""updated_user_model

Revision ID: e62ebfc75cab
Revises: a2bc3c7a9e6f
Create Date: 2026-06-22 11:03:52.976967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e62ebfc75cab'
down_revision = 'a2bc3c7a9e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('activation_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_activation_token'), ['activation_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_reset_token'), ['reset_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_reset_token'))
        batch_op.drop_index(batch_op.f('ix_users_activation_token'))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('reset_token')
        batch_op.drop_column('activation_token')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
